// <auto-generated />
using Infrastucture.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastucture.Data.Migrations
{
    [DbContext(typeof(InventarioContext))]
    [Migration("20230912005011_InitialMig")]
    partial class InitialMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Estites.Estado", b =>
                {
                    b.Property<string>("CodEstado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodPais")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("NomEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CodEstado");

                    b.HasIndex("CodPais");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("Core.Estites.Pais", b =>
                {
                    b.Property<string>("CodPais")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomPais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CodPais");

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("Core.Estites.Region", b =>
                {
                    b.Property<string>("CodRegion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodEstado")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("NomRegion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CodRegion");

                    b.HasIndex("CodEstado");

                    b.ToTable("Region", (string)null);
                });

            modelBuilder.Entity("Core.Estites.Estado", b =>
                {
                    b.HasOne("Core.Estites.Pais", "Pais")
                        .WithMany("Estados")
                        .HasForeignKey("CodPais");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Core.Estites.Region", b =>
                {
                    b.HasOne("Core.Estites.Estado", "Estado")
                        .WithMany("Regiones")
                        .HasForeignKey("CodEstado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Core.Estites.Estado", b =>
                {
                    b.Navigation("Regiones");
                });

            modelBuilder.Entity("Core.Estites.Pais", b =>
                {
                    b.Navigation("Estados");
                });
#pragma warning restore 612, 618
        }
    }
}
